### ISSUE TITLE
小程序接口是不是坏了。

### ISSUE THREAD

**Issue by Xiaocai9527** [zce/weapp-douban#1]
扫描二维码的小程序打开空白。

**Comment by zce** [comment]
这个问题是因为豆瓣的 API 服务对我搭建的反向代理服务有限制：单个 IP 每小时只能请求 100 次。

现已经提高到了每小时 10000 次，但是同样希望不要滥用，谢谢

**Comment by Xiaocai9527** [comment]
你误会我了，我昨天就用微信扫描那个二维码，以前都没用过就是进去就是空白。
刚才你回复我之后，我又去打开，才看到有数据出来。

**Comment by zce** [comment]
不是我没有理解，而是你没有理解~

白屏的原因是什么 → 自然是因为没有数据 → 没有数据的原因是什么 → 数据接口有问题 → 接口有什么问题 → 我给你的回复就是答案

**Comment by Xiaocai9527** [comment]
got it.
