### ISSUE TITLE
豆瓣api问题

### ISSUE THREAD

**Issue by zeromr** [zce/weapp-douban#2]
GET https://douban.uieee.com/v2/movie/in_theaters 400 (Bad Request)
{msg: "Invalid request", code: 999, request: "GET /v2/in_theaters"}
请问这个问题怎么解决啊，大佬……

**Comment by zce** [comment]
应该是你使用了错误的请求参数或者格式导致，你是不是应该提供完整的请求内容然后再说，因为单独在我这里请求这个代理是没有问题的

**Comment by zce** [comment]
ping @zeromr

**Comment by ouyangoliver** [comment]
我也是400，，bad request

**Comment by zce** [comment]
按照之前其他人的情况来说，应该是你们代码中对 Header 的设置问题

**Comment by ouyangoliver** [comment]
对对对，400是因为header的问题，改成Content-Type，小程序更新后要改成Content-Type。。谢谢zce前辈的分享，非常感谢
