### ISSUE TITLE
请问怎么解决豆瓣api中.webp格式图片在ios的显示？

### ISSUE THREAD

**Issue by konnga** [zce/weapp-douban#3]

**Comment by zce** [comment]
豆瓣的接口支持返回 `.jpg` 格式的图片，正常你通过 `wx.request`  发起的请求，所得到的数据中图片的格式就是 `.jpg`。服务端返回图片格式的依据是：Accept~

P.S. 这种问题类的交流，尽可能不要使用 issue，谢谢

**Comment by konnga** [comment]
好的，谢谢解答~
