### ISSUE TITLE
关于 search 接口的一些问题

### ISSUE THREAD

**Issue by ghost** [zce/weapp-douban#4]
您好，首先非常感谢您制作的镜像代理。 

最近我在使用 https://douban.uieee.com/v2/movie/search 接口的时候发现返回的 subjects 不管怎么都是空数组，在 h5 上访问豆瓣的 https://api.douban.com/v2/movie/search 请求可以返回得到 subjects 的结果。

因为我使用 https://douban.uieee.com/v2/movie/search 接口是在小程序端使用的，我也查看了您制作的豆瓣电影小程序，发现输入搜索之后也渲染不出列表了。请问是这个接口做了限制么。

十分期待您的解答。

**Comment by zce** [comment]
测试了一下，没有什么问题。

![image](https://user-images.githubusercontent.com/6166576/49861438-cb760a80-fe36-11e8-9989-b9bbdda96def.png)

![image](https://user-images.githubusercontent.com/6166576/49861476-e183cb00-fe36-11e8-83b6-b9c6b33c5907.png)

> 如果不是你代码的问题，那就有可能是 API Key 超额了 ;-)

**Comment by ghost** [comment]
十分感谢您的回复，那我再去检查一下是什么问题吧。

**Comment by mobyIsMe** [comment]
VM942:1  https://douban.uieee.com 不在以下 request 合法域名列表中，请参考文档：https://developers.weixin.qq.com/miniprogram/dev/framework/ability/network.html
这个网站被封了吗？

**Comment by zce** [comment]
@mobyIsMe 👋 你的这个问题与这个 issue 无关，你可以另起一个 issue~

> 小程序内部为了保证数据安全对程序代码中发起的请求类似白名单的限制，你需要将会被请求到的地址加入到你的**白名单**，也就是你所说的合法域名列表。

**Comment by zce** [comment]
ping @evenyao
